name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    uses: ./.github/workflows/ci.yml
  create-release:
    needs: build-release
    runs-on: ubuntu-20.04
    name: Create new release
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: compress artifacts
        run: |
          mkdir linux-amd64
          mv artifacts/pod-fluree-db-linux-amd64/pod-fluree-db-linux-amd64 linux-amd64/pod-fluree-db
          mkdir linux-arm64
          mv artifacts/pod-fluree-db-linux-arm64/pod-fluree-db-linux-arm64 linux-arm64/pod-fluree-db
          mkdir macos-amd64
          mv artifacts/pod-fluree-db-macos-amd64/pod-fluree-db-macos-amd64 macos-amd64/pod-fluree-db
          zip -j artifacts/pod-fluree-db-linux-amd64.zip linux-amd64/*
          zip -j artifacts/pod-fluree-db-linux-arm64.zip linux-arm64/*
          zip -j artifacts/pod-fluree-db-macos-amd64.zip macos-amd64/*
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.zip
